name: PyValidationTalk
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pandoc
  - marp-cli
  - ruff
  - isort
  - nbdime
  - pip
  - ipython
  - jupyterlab
  - matplotlib
  - notebook
  - numpy
  - pandas
  - pandera
  - polars
  - schema
  - pip:
    - -e .